[project]
name = "ninja-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "django-ninja>=1.4.3",
    "orjson>=3.11.3",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]
